name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          mkdir /opt/hostedtoolcache
      - name: Run web app
        run: |
          /usr/bin/python main.py
