name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          export RUNNER_ALLOW_RUNASROOT=true
          export AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache
          mkdir /opt/hostedtoolcache
      - name: Run web app
        run: |
          python main.py
